# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b7f5687cfe0592639d0d51069cd73107e5b5c3ea8f3e362111a7254dfb8f44fd2fc08be5e2073bd788c648e40dc8cdaf520f6f8bdf608ae7280f8e1f8e1a8a

test:
  secret_key_base: 3ef6d3ed70f4286c3a1a90ea32810ea0ce66d3cdcfc6246c9933b39664c77125579e71506348046f51eccda8ffe5ee34abe9f62438ef2579f282c34d2f8a1ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
